name: Opentrons App on Linux
on:
  workflow_dispatch:
    inputs:
      appimage-url:
        description: "Opentrons dmg URL."
        required: true
        default: "https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v4.5.0-linux-b12575.AppImage"
      chromedriver-version:
        description: "Chromedriver binary version."
        required: true
        default: "76.0.3809.126"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Get Opentrons AppImage and set env.EXECUTABLE_PATH
        run: |
          wget https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v4.5.0-linux-b12575.AppImage
          filename=$(basename ${{ github.event.inputs.appimage-url }})
          chmod +x $filename
          filepath=$(pwd)/$filename
          echo "EXECUTABLE_PATH=$filepath" >> $GITHUB_ENV
      - name: Install Chromedriver on the path.
        run: |
          chmod +x ./app-testing/ci-tools/linux_get_chromedriver.sh
          ./app-testing/ci-tools/linux_get_chromedriver.sh ${{ github.event.inputs.chromedriver-version }}
          chromedriver --version
      - name: Run docker robot
        run: docker-compose up -d
      - name: Install pyautogui dependencies.
        run: |
          sudo apt-get install -y python3-tk python3-dev scrot xauth
      - name: Install python dependencies.
        working-directory: ./app-testing
        run: |
          pip install pipenv==2020.8.13
          pipenv install --skip-lock
      - name: Run Tests.
        working-directory: ./app-testing
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          export EXECUTABLE_PATH=${{ env.EXECUTABLE_PATH }}
          export ROBOT_BASE_URL="http://127.0.0.1:31950"
          make test
      - name: Upload pytest test results.
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: app-testing/results/results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
